import re
import json

string = '''
    <option value="GLO">GLO - Global Affairs-Global Learning</option>
	<option value="AAS">AAS - African American &amp; African Std</option>
	<option value="ABG">ABG - Animal Biology Grad Gp</option>
	<option value="ABI">ABI - Animal Biology</option>
	<option value="ABT">ABT - Applied Biological System Tech</option>
	<option value="ACC">ACC - Professional Accountancy</option>
	<option value="AED">AED - Agricultural Education</option>
	<option value="AGC">AGC - Agricultural &amp; Envir Chem Grad</option>
	<option value="AHI">AHI - Art History</option>
	<option value="AMS">AMS - American Studies</option>
	<option value="ANB">ANB - Animal Behavior (Graduate Gp)</option>
	<option value="ANE">ANE - Med - Anesthesiology</option>
	<option value="ANG">ANG - Animal Genetics</option>
	<option value="ANS">ANS - Animal Science</option>
	<option value="ANT">ANT - Anthropology</option>
	<option value="APC">APC - VM Anatomy, Physiol &amp; Cell Bio</option>
	<option value="ARB">ARB - Arabic</option>
	<option value="ARE">ARE - Agricultural &amp; Resource Econ</option>
	<option value="ART">ART - Art Studio</option>
	<option value="ASA">ASA - Asian American Studies</option>
	<option value="AST">AST - Astronomy</option>
	<option value="ATM">ATM - Atmospheric Science</option>
	<option value="AVS">AVS - Avian Sciences</option>
	<option value="BAX">BAX - Business Analytics</option>
	<option value="BCB">BCB - Bio, Molec, Cell, Dev Bio GG</option>
	<option value="BCM">BCM - Med - Biological Chemistry</option>
	<option value="BIM">BIM - Engineering Biomedical</option>
	<option value="BIS">BIS - Biological Sciences</option>
	<option value="BIT">BIT - Biotechnology</option>
	<option value="BPH">BPH - Biophysics (Graduate Group)</option>
	<option value="BPT">BPT - Biophotonics</option>
	<option value="BST">BST - Biostatistics</option>
	<option value="CAR">CAR - Med - Intrl: Cardiology</option>
	<option value="CDM">CDM - Cinema and Digital Media</option>
	<option value="CGS">CGS - Cognitive Science</option>
	<option value="CHA">CHA - Med - Cell Biol &amp; Human Anat</option>
	<option value="CHE">CHE - Chemistry</option>
	<option value="CHI">CHI - Chicano Studies</option>
	<option value="CHN">CHN - Chinese</option>
	<option value="CLA">CLA - Classics</option>
	<option value="CLH">CLH - Clinical Research</option>
	<option value="CMN">CMN - Communication</option>
	<option value="CNS">CNS - Consumer Sciences</option>
	<option value="COM">COM - Comparative Literature</option>
	<option value="CRD">CRD - Community &amp; Regional Develpmnt</option>
	<option value="CRI">CRI - Critical Theory (Desig Emphas)</option>
	<option value="CST">CST - Cultural Studies</option>
	<option value="CTS">CTS - Cinema &amp; Technocultural Stud</option>
	<option value="DEB">DEB - Biotechnology (Desig Emphasis)</option>
	<option value="DER">DER - Med - Dermatology</option>
	<option value="DES">DES - Design</option>
	<option value="DRA">DRA - Dramatic Art</option>
	<option value="DVM">DVM - Veterinary Clinical Rotation</option>
	<option value="EAD">EAD - Engineering Applied Sci-Davis</option>
	<option value="EAE">EAE - Engineering Aerospace Sci</option>
	<option value="EAP">EAP - Education Abroad Program</option>
	<option value="EAS">EAS - East Asian Studies</option>
	<option value="EBS">EBS - Engineering Biological Systems</option>
	<option value="ECH">ECH - Engineering Chemical</option>
	<option value="ECI">ECI - Engineering Civil &amp; Environ</option>
	<option value="ECL">ECL - Ecology</option>
	<option value="ECN">ECN - Economics</option>
	<option value="ECS">ECS - Engineering Computer Science</option>
	<option value="EDU">EDU - Education</option>
	<option value="EEC">EEC - Engineering Electrical &amp; Compu</option>
	<option value="EGG">EGG - Energy Systems</option>
	<option value="EME">EME - Engineering Mechanical</option>
	<option value="EMR">EMR - Med - Intrl: Emergency Med</option>
	<option value="EMS">EMS - Engineering Materials Science</option>
	<option value="ENG">ENG - Engineering</option>
	<option value="ENH">ENH - Environmental Horticulture</option>
	<option value="ENL">ENL - English</option>
	<option value="ENM">ENM - Med - Intrl: Endocrinol &amp;Metab</option>
	<option value="ENT">ENT - Entomology</option>
	<option value="ENV">ENV - Environmental Policy &amp; Mgmt</option>
	<option value="EPI">EPI - Epidemiology (Graduate Group)</option>
	<option value="ESM">ESM - Environmental Sci &amp; Management</option>
	<option value="ESP">ESP - Environmental Science &amp; Policy</option>
	<option value="ETX">ETX - Environmental Toxicology</option>
	<option value="EVE">EVE - Evolution and Ecology</option>
	<option value="EXB">EXB - Exercise Biology</option>
	<option value="EXS">EXS - Exercise Science</option>
	<option value="FAH">FAH - Fine Arts &amp; Humanities</option>
	<option value="FAP">FAP - Med - Family Practice</option>
	<option value="FMS">FMS - Film Studies</option>
	<option value="FOR">FOR - Forensic Science</option>
	<option value="FPS">FPS - Fiber And Polymer Science</option>
	<option value="FRE">FRE - French</option>
	<option value="FRS">FRS - Freshman Seminar</option>
	<option value="FSE">FSE - Future Undergrad Sci Educators</option>
	<option value="FSM">FSM - Food Service Management</option>
	<option value="FST">FST - Food Science &amp; Technology</option>
	<option value="GAS">GAS - Med - Intrl: Gastroenterology</option>
	<option value="GDB">GDB - Global Disease Biology</option>
	<option value="GEL">GEL - Geology</option>
	<option value="GEO">GEO - Geography</option>
	<option value="GER">GER - German</option>
	<option value="GGG">GGG - Genetics (Graduate Group)</option>
	<option value="GMD">GMD - Med - Intrl: General Medicine</option>
	<option value="GRD">GRD - Graduate Education</option>
	<option value="GRK">GRK - Greek</option>
	<option value="GSW">GSW - Gender, Sexuality &amp; Women Stdy</option>
	<option value="HDE">HDE - Human Development</option>
	<option value="HEB">HEB - Hebrew</option>
	<option value="HIN">HIN - Hindi/Urdu</option>
	<option value="HIS">HIS - History</option>
	<option value="HMR">HMR - Human Rights</option>
	<option value="HNR">HNR - Honors Challenge</option>
	<option value="HON">HON - Med - Intrl: Hematology-Oncol</option>
	<option value="HPH">HPH - Med - Human Physiology</option>
	<option value="HRT">HRT - Horticulture</option>
	<option value="HUM">HUM - Humanities</option>
	<option value="HYD">HYD - Hydrologic Science</option>
	<option value="IAD">IAD - International Agricultural Dev</option>
	<option value="ICL">ICL - International Commercial Law</option>
	<option value="IDI">IDI - Med - Intrl: Infectious Dis</option>
	<option value="IMD">IMD - Med - Internal Medicine</option>
	<option value="IMM">IMM - Immunology (Graduate Group)</option>
	<option value="IRE">IRE - International Relations</option>
	<option value="IST">IST - Integrated Studies</option>
	<option value="ITA">ITA - Italian</option>
	<option value="JPN">JPN - Japanese</option>
	<option value="JST">JST - Jewish Studies</option>
	<option value="LAT">LAT - Latin</option>
	<option value="LAW">LAW - Law</option>
	<option value="LDA">LDA - Landscape Architecture</option>
	<option value="LIN">LIN - Linguistics</option>
	<option value="LTS">LTS - College of Letters &amp; Science</option>
	<option value="MAE">MAE - Engineering Mechanical &amp; Aero</option>
	<option value="MAT">MAT - Mathematics</option>
	<option value="MCB">MCB - Molecular and Cellular Biology</option>
	<option value="MCN">MCN - Maternal and Child Nutrition</option>
	<option value="MCP">MCP - Molecular, Cell &amp; Int Physio</option>
	<option value="MDS">MDS - Med - Medical Science</option>
	<option value="MGB">MGB - Management Work Prof Bay Area</option>
	<option value="MGP">MGP - Management Working Professionl</option>
	<option value="MGT">MGT - Management</option>
	<option value="MGV">MGV - Management - Online</option>
	<option value="MHI">MHI - Health Informatics</option>
	<option value="MIB">MIB - Microbiology (Graduate Group)</option>
	<option value="MIC">MIC - Microbiology</option>
	<option value="MMI">MMI - Med - Medical Microbiology</option>
	<option value="MPM">MPM - VM Preventive Veterinary Med</option>
	<option value="MPS">MPS - Math &amp; Physical Sciences</option>
	<option value="MSA">MSA - Middle East/South Asian Std</option>
	<option value="MSC">MSC - Military Science</option>
	<option value="MST">MST - Medieval Studies</option>
	<option value="MUS">MUS - Music</option>
	<option value="NAS">NAS - Native American Studies</option>
	<option value="NEM">NEM - Nematology</option>
	<option value="NEP">NEP - Med - Intrl: Nephrology</option>
	<option value="NEU">NEU - Med - Neurology</option>
	<option value="NGG">NGG - Nutrition Graduate Group</option>
	<option value="NPB">NPB - Neurobiology,Physio &amp; Behavior</option>
	<option value="NRS">NRS - Nursing</option>
	<option value="NSC">NSC - Neuroscience (Graduate Group)</option>
	<option value="NSU">NSU - Med - Neurosurgery</option>
	<option value="NUB">NUB - Nutritional Biology (Grad Grp)</option>
	<option value="NUT">NUT - Nutrition</option>
	<option value="OBG">OBG - Med - Obstetrics &amp; Gynecology</option>
	<option value="OPT">OPT - Med - Ophthalmology</option>
	<option value="OSU">OSU - Med - Orthopaedic Surgery</option>
	<option value="OTO">OTO - Med - Otolaryngology</option>
	<option value="PAS">PAS - Physician Assistant Studies</option>
	<option value="PBG">PBG - Population Biology</option>
	<option value="PBI">PBI - Plant Biology (Graduate Group)</option>
	<option value="PED">PED - Med - Pediatrics</option>
	<option value="PER">PER - Persian</option>
	<option value="PFS">PFS - Performance Studies (Grad Grp)</option>
	<option value="PHA">PHA - Med - Medical Pharmacol &amp;Toxic</option>
	<option value="PHE">PHE - Physical Education</option>
	<option value="PHI">PHI - Philosophy</option>
	<option value="PHR">PHR - VM Population Health &amp; Reprod</option>
	<option value="PHY">PHY - Physics</option>
	<option value="PLB">PLB - Plant Biology</option>
	<option value="PLP">PLP - Plant Pathology</option>
	<option value="PLS">PLS - Plant Science</option>
	<option value="PMD">PMD - Med - Pathology</option>
	<option value="PMI">PMI - VM Pathology, Microbiol &amp;Immun</option>
	<option value="PMR">PMR - Med - Physical Medicine &amp;Rehab</option>
	<option value="POL">POL - Political Science</option>
	<option value="POR">POR - Portuguese</option>
	<option value="PSC">PSC - Psychology</option>
	<option value="PSU">PSU - Med - Plastic Surgery</option>
	<option value="PSY">PSY - Med - Psychiatry</option>
	<option value="PTX">PTX - Pharmacology-Toxicology (Grad)</option>
	<option value="PUL">PUL - Med - Intrl: Pulmonary</option>
	<option value="PUN">PUN - Punjabi</option>
	<option value="RDI">RDI - Med - Radiology (Diagnostic)</option>
	<option value="REL">REL - Study of Religion</option>
	<option value="RNU">RNU - Med - Radiology-Nuclear Med</option>
	<option value="RON">RON - Med - Radiation Oncology</option>
	<option value="RST">RST - Religious Studies</option>
	<option value="RUS">RUS - Russian</option>
	<option value="SAF">SAF - Sustainable Ag &amp; Food Sys</option>
	<option value="SAS">SAS - Science and Society</option>
	<option value="SOC">SOC - Sociology</option>
	<option value="SPA">SPA - Spanish</option>
	<option value="SPH">SPH - Med - Public Health Sciences</option>
	<option value="SSC">SSC - Soil Science</option>
	<option value="STA">STA - Statistics</option>
	<option value="STH">STH - Social Theory &amp; Compar History</option>
	<option value="STS">STS - Science &amp; Technology Studies</option>
	<option value="SUR">SUR - Med - Surgery</option>
	<option value="TAE">TAE - Agricultural &amp;​ Environmental Technology</option>
	<option value="TCS">TCS - Technocultural Studies</option>
	<option value="TTP">TTP - Transportation Tech &amp; Policy</option>
	<option value="TXC">TXC - Textiles &amp; Clothing</option>
	<option value="URO">URO - Med - Urology</option>
	<option value="UWP">UWP - University Writing Program</option>
	<option value="VEN">VEN - Viticulture &amp; Enology</option>
	<option value="VET">VET - School of Veterinary Medicine</option>
	<option value="VMB">VMB - VM Molecular Biosciences</option>
	<option value="VMD">VMD - Veterinary Medicine</option>
	<option value="VSTN">VSTN - VSTN</option>
	<option value="WAS">WAS - Washington Center</option>
	<option value="WFC">WFC - Wildlife, Fish &amp; Conserv Biol</option>
	<option value="WLD">WLD - Workload</option>
	<option value="WMS">WMS - Women's Studies</option>
'''

# Use regular expressions to extract the option values
option_values = re.findall(r'value="([^"]+)', string)

with open("vite-super-secret\Backend\Web Scraper\data\course_category.json", "w") as f:
    json.dump(option_values, f); 
print(option_values)
